# Site
name: "Frankyston Lins"
title: "Frankyston Lins"
description: "Blog do Frankyston Lins"
meta_description: "blog, frankyston, rails, ruby, development"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: ""
google_analytics: "UA-46278016-1"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  frankyston:
    name: Frankyston Lins Nogueira
    display_name: Frankyston Lins
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: frankyston@gmail.com
    web: https://frankyston.dev
    twitter: https://twitter.com/frankyston
    description: "Desenvolvedor Ruby on Rails, gosto de games e tocar violão nas horas vagas."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
